name: nike_store
description: Nike store Application Using Flutter
# CodeWithFlexz

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  insta_like_button: ^0.1.1 # External package

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - images/jordanmars.jpg
    - images/lebron18.jpg
    - images/MCTrainer.jpg
    - images/SIGNALDMX.jpg
    - images/nike-logo.png
    - images/1.jpg
    - images/2.jpg
    - images/3.jpg
    - images/4.jpg
    - images/5.jpg
    - images/6.jpg
